const JUICE_WRLD_QUOTES = [
  "I still see your shadows in my room.",
  "Who knew evil girls have the prettiest face?",
  "You left me falling and landing inside my grave.",
  "We're all in this together, we all stuck forever.",
  "Sometimes life's a mess, I get myself up through the darkest days.",
  "I know my heart is blank, and I'll never have you to thank.",
  "I was raised inside a jungle, I came out a lion.",
  "Music is my therapy — I put everything I feel into a song.",
  "I freestyle a lot of my songs; that's how I catch the vibe.",
  "If anybody's going through anything, I hope my music helps them feel less alone.",
  "I wanna change, but I can't tell no one.",
  "You gave me a heart that was full of mistakes.",
  "I know that the truth is hard to digest.",
  "I know you miss me, who don't?",
  "They tell me I'ma be a legend, I don't want that title now.",
  "I'm a rockstar, smash my guitar on a cop car.",
  "I don't wanna pretend we're something, we nothing.",
  "Used to think I was cool, now I'm just trying to feel whole.",
  "I take prescriptions to make me feel a-okay.",
  "I know it's all my fault, I can't make you stay.",
  "I'm my own worst enemy.",
  "I chase these pills 'cause they don't chase me back.",
  "The truth is hard to digest, five or six pills in my right hand.",
  "I pour my heart out on every track.",
  "All girls are the same, they're rotting my brain.",
  "Legends never die — they live on in the music.",
  "I'd do anything in my power to see you smile.",
  "I don't got nobody, but I'm never lonely.",
  "My mind is foggy, I'm so confused.",
  "I made it out the storm, I'm still standing.",
  "She told me to put my heart in the bag and nobody gets hurt.",
  "I'm running from her love, I'm not fast so I'm making it worse.",
  "I have these lucid dreams where I can't move a thing.",
  "You were my everything, thoughts of a wedding ring.",
  "Easier said than done, I thought you were the one.",
  "You found another one, but I am the better one.",
  "What's the 27 club? We ain't making it past 21.",
  "All legends fall in the making.",
  "Ain't nothing like the feeling of uncertainty, the eeriness of silence.",
  "I can't breathe, I'm waiting for the exhale.",
  "Toss my pain with my wishes in a wishing well.",
  "Drugs killing me softly, Lauryn Hill.",
  "Sometimes I don't know how to feel.",
  "Ring-ring, phone call from depression.",
  "This is the part where I tell you I'm fine, but I'm lying.",
  "Exhale depression as the wind blows. These are the laws of living in vogue.",
  "We're perfectly imperfect children. Rose from the dust, all of us are on a mission.",
  "Telling you right now, all you'll find is a lost soul, rich and blind.",
  "It's funny how the blessed ones had the most curses.",
  "Finally know the difference between love and drugs.",
  "Drugs got me sweating, but the room getting colder.",
  "Heartbreak's a hard thing to deal with, but I've got art as my heart's shield.",
  "My anxiety the size of a planet.",
  "I've been through the wringer, tryna put a diamond ring on her finger.",
  "What's the point of living if you ain't living a dream?",
  "I don't know if it's because my heart hurts or if I am insecure.",
  "You done woke me up from my eternal slumber, I'm the lightning you're the thunder.",
  "You can see the pain in my laugh. Demons coming back from the past.",
  "I'm a rockstar in his prime.",
  "I don't need another heartbreak.",
  "I talk about you all the time. But you just listen, you never reply.",
  "Tell me why I'm waiting for someone that couldn't give a fuck about me.",
  "I chase thrills, you still crashin' Hot Wheels.",
  "I'm running to the money all the time so I can never be late.",
  "If you ain't payin' a hundred thousand, get them features out my face.",
  "I just walked in the building, look like a million, but I'm worth more than a million.",
  "I'm running out of options, it ain't a lot of options.",
  "I problem solve with Styrofoam, my world revolves around a black hole.",
  "Date me, break me, easily replace me. Hopefully you see it clear, hopefully it's HD.",
  "Now I'm insane, demons in my brain.",
  "You make me want to start smoking cigarettes, so I die slowly.",
  "I can't go to sleep without her next to me.",
  "Roses are red, violets are blue, my heart is dead, I'm such a fool.",
  "I'm a hostage to my thoughts.",
  "Every day's a battle with my brain.",
  "I'm not okay, I'm just dealing.",
  "The world is yours if you want it.",
  "We're all dying, it's just a matter of time.",
  "Feel like I'm outta my mind, it feel like my life ain't mine.",
  "I'm scared to fall in love again.",
  "The world we know is behind closed doors. My demons hide when I feel alive.",
  "I'm trying to find my peace, I've been broken for a while.",
  "Life's not fair, but I'm here.",
  "I got pain in my heart, I told you a hundred times.",
  "When heart breaks it feel like the world's gone, but if the love's real, you'd feel your soul roar like a lion.",
  "I belong with the one put on this earth for me.",
  "I go through so much, I'm 19 years old. It's been months since I felt at home.",
  "I'm running out of patience, hope you can understand that.",
  "I made mistakes, but that's what life is about; my mistakes led me to a better route.",
  "Words have a lot of power.",
  "Music is the best way that I can communicate with other people.",
  "It is hard to separate the art from the artist.",
  "Nobody on this earth is perfect. Everybody has their flaws; everybody has their dark secrets and vices.",
  "A minor setback paves the way for a major comeback.",
  "I know I have a purpose, but I don't see the purpose.",
  "I'll never forget about the demons I conquered.",
  "Everybody stay positive no matter how negative life gets.",
  "I wanna be more than a millionaire. I wanna change the world.",
  "I feel like I inspire more people than I think I do. I just need to remember that.",
  "I'm a music head and always will be.",
  "I freestyle everything.",
  "Whatever you want to do in life, find something that you don't mind doing for the rest of your life.",
  "Don't let the scale define you. Be active. Eat healthy. Be happy.",
  "That's what makes you a real man, though. You not running from how you feel?",
  "It's all about progression. Evolution. You can't be afraid to evolve.",
  "I speak from the perspective of saying, 'You are not alone. I'm fighting this fight with you.'",
  "People will do you wrong over and over, but the one time you call them out you're suddenly the bad guy.",
  "Being like everybody else won't really get you anywhere.",
  "Life is the only thing besides love that holds more value than any currency.",
  "Thank you, God, for waking me up when you ain't have to. This life is a blessing.",
  "I think it's important to add a personal aspect to your music — that's what makes it authentic.",
  "Words can be as sweet as candy or as sharp as a blade. That's the beauty of it.",
  "You can't change the past, but you can shape your future.",
  "My goal in life isn't to live forever, but to create something that will.",
  "Dreams turn into reality if you make them.",
  "Never been afraid to die but I always been afraid to die before I get where I'm going.",
  "I refuse to die, not by your side. So I'll take what I can from you and hide.",
  "Success is me waking up every day and being able to do whatever the fuck I want comfortably.",
  "Throughout life, there's always gonna be discouraging people, but you just gotta stay true to yourself.",
  "I try my best to make music that doesn't have an expiration date.",
  "I like to call myself an artist who can tap into a lot of different sounds.",
  "All I ever wanted was real love.",
  "You brought meaning to my life, all because of you I do right.",
  "I'm still standing, better than how I found you.",
  "The people I looked up to put their demons out there. They provided a path for me to walk on.",
  "A lot of people that get into my position change up, become fake, become paranoid. I'm still the same person.",
  "It's good to put money back into communities.",
  "I don't want nobody to think that I'm an asshole. I don't try to be mean on purpose.",
  "One thing my dad told me was, never let your woman know when you're insecure.",
  "If you ever get jealous, just remember I chose you out of everyone else.",
];

function randomQuote() {
  return JUICE_WRLD_QUOTES[Math.floor(Math.random() * JUICE_WRLD_QUOTES.length)];
}

module.exports = { randomQuote };
